qiime2/q2cli

README.md
q2cli/__init__.py
q2cli/cli.py
setup.py

ENH: initial structure, dynamic generation of commands

---

README.md
q2cli/cli.py

Currently **very** slow, track progress on #6.
Fixes #5. Also removes context usage in favor of global plugin manager.

ENH: bash tab completion!

---

q2cli/cli.py

@jairideout, @ebolyen this one is ready (depends on qiime2/qiime2#62, so that should be merged first).

MAINT: moved metadata parsing to framework

---

q2cli/_info.py
q2cli/_tools.py
q2cli/cli.py
setup.py

* Adds ``info`` command which provides ``print_qiime_config.py``-like information
* Adds ``tools`` group which contains ``extract`` and ``view`` (#17) (and will contain ``import`` soon)
* Adds method/visualizer name and description as short_help and help, respectively (#16)
* Removes ``--plugins`` and ``--info`` parameters, as this functionality is now accessible in ``qiime info``.

various enhancements

---

q2cli/_info.py
q2cli/_tools.py
q2cli/cli.py

Also contains some flake8 fixes - the repo doesn't currently have travis running, so some flake8 issues snuck in.

option names have underscores converted to dashes

---

.travis.yml
q2cli/cli.py
q2cli/tests/test_cli.py

TST: adds initial testing of cli

---

q2cli/cli.py

Previous option order was stochastic.
Revert this commit when https://github.com/qiime2/qiime2/issues/70 is fixed.

ENH: sort plugin command options alphabetically within inputs, parameters, and output groups

---

q2cli/cli.py

Metadata starts with `--m` and parameters with `--p`.

ENH: prefix parameters

---

.travis.yml
q2cli/_info.py

Utilizes API provided by qiime2/qiime2/issues/80
**Tests depend on either a new QIIME 2 release to conda or swapping QIIME 2 to fetch from the GitHub master branch.**

ENH: Import urls from qiime.sdk

---

q2cli/commands.py
q2cli/handlers.py

Enables users to specify a config file containing values which will
be used as the options for their command.

ENH: Adds `cmd-config` option to cli

---

q2cli/commands.py

BUG: fixed duplicate command on action

---

q2cli/handlers.py

I've added support for Bool primitive in the standard click way. There are other ways to do it, so please let me know if you would like something different.

ENH: added bool as for #52

---

q2cli/commands.py
q2cli/handlers.py

I've added support for Bool primitive in the [standard click way](http://click.pocoo.org/5/options/#boolean-flags). There are other ways to do it, so please let me know if you would like something different.

ENH: added default argument support

---

q2cli/tools.py

ENH: `qiime tools extract` displays extracted directory

---

q2cli/tools.py

Example:
```shell
$ qiime tools peek feature-table-frequency.qza
UUID:        31982de9-7469-4f2a-85f7-40b3bc176db9
Type:        FeatureTable[Frequency]
Data format: BIOMV100DirFmt
$ qiime tools peek viz.qzv
UUID:        1ebd0cd5-1e23-42ed-b5e1-59fa10c37192
Type:        Visualization
Data format: Visualization
$
```
The first column is colored green.
Fixes #69.

ENH: `qiime tools peek`

---

q2cli/info.py
q2cli/tools.py

ENH: add `qiime info --citations` flag, remove `qiime tools citations`

---

q2cli/__main__.py
q2cli/commands.py
q2cli/completion.py

REF: set root command help using decorator instead of within constructor

---

q2cli/tools.py

ENH: update language for qiime tools view

---

q2cli/tools.py

Adds `qiime tools export --input-path PATH --output-path PATH [--format QIIME2Format]`
Relies on qiime2/qiime2/pull/172

ENH: Add qiime tools export

---

q2cli/cache.py
q2cli/commands.py
q2cli/handlers.py

Adds help text functionality on all methods and visualizers.
Relies on qiime2/qiime2/pull/196

ENH: Add parameter help text support

---

q2cli/cache.py

Cache requirements file is now written after all other parts of the cache to avoid creating a newer version of the requirements that doesn't match the previous state.json.
This fixes the case where a user ran q2cli with a functioning QIIME deployment (thus creating a valid cache), and then installed a new plugin and ran q2cli again. A cache refresh was triggered, and if the plugin failed to load for whatever reason, a new requirements file had already been written, and this newer requirements file was out-of-sync with the state.json file that existed from the previous deployment. Thus, the new plugin wouldn't display in the CLI even if the plugin loading problems were resolved because the cache wouldn't be refreshed.
Fixes #88.

BUG: avoid outdated cache on plugin loading failure

---

q2cli/commands.py

ENH: pretty errors

---

q2cli/tools.py

BUG: Not all macOS machines have a $DISPLAY set

---

q2cli/info.py

ENH: Add QIIME 2 Release to qiime info

---

q2cli/commands.py

Changes behavior to write to a temporary file on error, allowing users to retrieve the information without needing to rerun the process using `--verbose`.
Resolves #127

ENH: Store error on runs without verbose

---

q2cli/handlers.py

This is another bit pair-programmed with @ebolyen .  This basically makes the CLI aware of the metadata artifact

WIP: Metadata artifact

---

q2cli/tests/test_cli.py

Relies on https://github.com/qiime2/qiime2/pull/272

TST: add unit tests for methods without inputs

---

q2cli/tests/__init__.py

TST/BUG: missing __init__.py

---

q2cli/handlers.py

Please tell me there is a safer way to perform this check, @ebolyen & @jairideout...
Fixes #156

BUG: Stop labeling output Viz as Artifacts

---

q2cli/commands.py
q2cli/tools.py
q2cli/util.py

Probably needs some tests still

ENH: pretty import errors

---

q2cli/cache.py
q2cli/commands.py

Options now follow the action's signature order so that required options are listed first, followed by optional options, outputs, and builtins.

ENH: CLI options match action signature order

---

q2cli/handlers.py

Now displays pretty error messages with better hints at what might be going wrong.
Fixes #158.
Examples:

BUG: improve error reporting when loading metadata

---

q2cli/tests/test_cli.py
q2cli/tools.py

Depends on https://github.com/qiime2/qiime2/pull/347

ENH: qiime tools validate

---

q2cli/handlers.py
q2cli/util.py

ENH: Add `Set` support

---

q2cli/commands.py
q2cli/handlers.py
q2cli/tests/test_tools.py
q2cli/tools.py
q2cli/util.py

fixes #177
fixes #165 
---
---

ENH: adds `inspect-metadata` and cleans up errors

---

q2cli/tests/test_cli.py

Depends on https://github.com/qiime2/qiime2/pull/371

MAINT: update unit test to match Metadata writer number formatting

---

q2cli/cache.py
q2cli/commands.py
q2cli/info.py
q2cli/tools.py
q2cli/util.py

Depends on https://github.com/qiime2/qiime2/pull/389

ENH: adds citations tool and flags

---

q2cli/tools.py

Fixed a small typo in help on line 147

Fixed typo in help

---

q2cli/tests/test_cli.py
q2cli/tests/test_tools.py
q2cli/tools.py

Fixes #190 
Fixes #191 
Fixes #194

ENH: q2cli import & extract API cleanup and minor typo fix

---

Makefile
hooks/activate_q2cli_tab_completion.sh

Adds automatic tab completion when using ZSH or bash after activating the conda environment.

NEW: automatic tab completion on env activation

---

q2cli/commands.py

Also show package in plugin --version (fixes #207)

---

q2cli/core/cache.py

BUG: Handle composite primitives

---

LICENSE
q2cli/__init__.py
q2cli/__main__.py
q2cli/builtin/__init__.py
q2cli/builtin/dev.py
q2cli/builtin/info.py
q2cli/builtin/tools.py
q2cli/click/__init__.py
q2cli/click/command.py
q2cli/click/option.py
q2cli/click/parser.py
q2cli/click/type.py
q2cli/commands.py
q2cli/core/__init__.py
q2cli/core/cache.py
q2cli/core/completion.py
q2cli/core/config.py
q2cli/tests/__init__.py
q2cli/tests/test_cli.py
q2cli/tests/test_core.py
q2cli/tests/test_dev.py
q2cli/tests/test_tools.py
q2cli/util.py
setup.py

Updated the copyright headers to reflect the current year.

MAINT: Updated copyright headers to 2020

---

q2cli/click/type.py

I was on the edge of my seat waiting to see what else was wrong...

BUG: minor typo in column retrieval error msg

---

q2cli/tests/test_cli.py

To fix: https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/unit-test-q2cli/builds/61

MAINT: update assertion for Click 7.1

---

q2cli/click/type.py
q2cli/tests/test_cli.py

Fixes #240 
@ebolyen - I could use a hand on this, if you get a chance - I'm not sure what the "right" way is to report the traceback back to the user. I hacked something into place, but I have a hunch there is a better way...

BUG: stop swallowing certain Result errors

---

q2cli/core/usage.py

See https://github.com/qiime2/qiime2/issues/544.
Depends on https://github.com/qiime2/qiime2/pull/546.

BUG: Remove * from records.

---

README.md
hooks/50_activate_q2cli_tab_completion.sh
q2cli/__main__.py

BUG: resolved tab auto-complete in zsh

---

q2cli/core/cache.py
q2cli/core/usage.py
q2cli/tests/test_mystery_stew.py
q2cli/tests/test_usage.py

~~depends on https://github.com/qiime2/qiime2/pull/603~~
~~depends on https://github.com/qiime2/qiime2/pull/604~~
depends on https://github.com/qiime2/qiime2/pull/608

maint: usage driver cleanup

---

q2cli/core/usage.py

I believe this will work. @gregcaporaso can you test this branch on your example?

BUG: fix Usage.view_as_metadata

---

q2cli/click/type.py

Addresses issue found in https://github.com/qiime2/q2-mystery-stew/pull/32

TST: fix issue with view_as_metadata and mystery-stew

---

q2cli/core/usage.py

Closes https://github.com/qiime2/qiime2/issues/612
Closes https://github.com/qiime2/qiime2/issues/613

Minor tweaks impacting usage

---

q2cli/builtin/tools.py
q2cli/click/type.py
q2cli/commands.py
q2cli/tests/test_cache_cli.py
q2cli/tests/test_cli.py
q2cli/tests/test_tools.py
q2cli/util.py

Start adding cli support for the cache so it can enter wider use

NEW: First pass at cli for cache

---

q2cli/builtin/tools.py
q2cli/tests/test_tools.py

Adds cache utilities to `qiime tools cache-` on the cli.

NEW: Start adding cache tools to the cli

---

q2cli/builtin/tools.py
q2cli/click/option.py
q2cli/click/type.py
q2cli/commands.py
q2cli/tests/test_cache_cli.py
q2cli/tests/test_cli.py
q2cli/util.py

Adds cli support for output collections.

Output collections

---

q2cli/click/option.py
q2cli/commands.py
q2cli/tests/test_cache_cli.py
q2cli/tests/test_cli.py
q2cli/tests/test_tools.py
q2cli/util.py

Adds support for pipeline resumption to the cli

Pipeline resumption

---

q2cli/click/option.py
q2cli/commands.py
q2cli/tests/test_cache_cli.py
q2cli/tests/test_cli.py

Clean up some issues with parsl and stuff on q2cli

Some cleanup

---

q2cli/builtin/tools.py
q2cli/commands.py

Will merge via CLI once ready.

2023.5 patch fixes

---

q2cli/click/option.py

ensure keys are strings

---

q2cli/commands.py
q2cli/tests/data/mapping_config.toml
q2cli/tests/test_cache_cli.py

Changes to go along with qiime2/qiime2#695. Blocked by qiime2/qiime2#695

Fixes here to go along with framework changes

---

q2cli/click/option.py
q2cli/click/type.py
q2cli/core/usage.py
q2cli/tests/test_usage.py

CLI pairing to [#691](https://github.com/qiime2/qiime2/pull/691)
Co-Authored by: @Oddant1

NEW: adds ResultCollection to Usage Driver
