qiime2/q2cli

- q2cli/cli.py
Stops commands from being displayed if their associated plugin does not have methods or a visualizer
> Remove types

- q2cli/cli.py
As an example:
```bash
$ qiime types feature-table --help
feature-table is not a valid command for plugin types.
```
Whereas the prior behavior was:
```bash
$ qiime types feature-table --help
Traceback (most recent call last):
File "/Users/mcdonadt/miniconda3/envs/q2test/bin/qiime", line 6, in <module>
sys.exit(q2cli.cli.main())
File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/q2cli-0.0.1-py3.5.egg/q2cli/cli.py", line 242, in main
File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/click/core.py", line 716, in __call__
return self.main(*args, **kwargs)
File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-packages/click/core.py", line 696, in main
rv = self.invoke(ctx)
File "/Users/mcdonadt/miniconda3/envs/q2test/lib/python3.5/site-pac …
```
> ENH: more user friendly message when a command doesn't exist

- q2cli/_tools.py
Having the Return key exit was problematic if the user had a newline on the end of their command or accidentally hit Return soon after running the command (I do this all the time).
> ENH: quit visualization viewing with 'q' key, Control-C, and Control-D

- q2cli/cli.py
Now does not have an opinion on the metadata axis it receives.
Pair-programmed with @jakereps.
> DOC: make metadata/metadata category option help text more general

- q2cli/_info.py
- q2cli/_tools.py
- q2cli/cli.py
- setup.py
Here's what this looks like...
``qiime info`` tells you how to access all citations:
which looks like the following: 
(A little bit ugly, but it's a big text dump so I don't really know how to get around it. We can optionally present subsets to the user in the future.)
Calling ``--help`` on a plugin also presents the citation, the website, and how to get help:
> ENH: support discovery of plugin citations and user support text

- q2cli/commands.py
- q2cli/handlers.py
- q2cli/tests/test_cli.py
Supports actions generically instead of separate handling of methods and visualizers. Supports flexible handling of output file extensions that will work when pipeline actions and new result types are added to the framework in the future.
Depends on https://github.com/qiime2/qiime2/pull/118 being merged.
> ENH/REF/MAINT: use new "actions" API; flexible support for output file extensions

- q2cli/handlers.py
I tested this locally by modifying an existing method to have a default parameter of `None`. 
This depends on qiime2/qiime2#158
> ENH: adds support for None as a default value

- q2cli/handlers.py
Displays "[required]" for required inputs and parameters, "[optional]" for parameters with a default value of None, and "[default: <value>]" for parameters with a default value that isn't None.
Additionally, the input and output options are formatted as "Artifact: <type repr>". Output options now describe their usage with --output-dir.
> ENH: more descriptive option help text (e.g. required vs optional)

- q2cli/__main__.py
- q2cli/cache.py
- q2cli/commands.py
- q2cli/dev.py
- q2cli/handlers.py
- q2cli/info.py
- q2cli/tests/test_cli.py
- q2cli/tools.py
- q2cli/util.py
Previously, any CLI command would take ~3 seconds (tested with q2-types, q2-feature-table, q2-diversity, q2-emperor installed). The CLI was virtually unusable and tab-completion (as provided out of the box by Click) was even more unusable. This poor performance would have scaled with the number of installed plugins.
Now, the CLI caches its state to a system-specific config directory. The cache is automatically refreshed when a change is made to the current QIIME deployment (e.g. a plugin is uninstalled, a new plugin is installed, a plugin version changes, or the version of q2cli changes).
There are two mechanisms (mainly for developers) to force a cache refresh: the `qiime dev refresh-cache` command, or setting the Q2CLIDEV environment variable to any value. Devs will need to use one of …
> ENH: cached CLI state for performance improvements

- q2cli/__main__.py
- q2cli/info.py
Example:
```shell
$ qiime --version
q2cli version 0.0.3
Run `qiime info` for more version details.
```
Fixes #68.
> ENH: faster `qiime --version` flag with shorter output

- q2cli/handlers.py
Processing of boolean flags was broken in master. I discovered this by running ``qiime dada2 denoise`` and getting the following:
```
raise TypeError('Got secondary option for non boolean flag.')
```
The [docs](http://click.pocoo.org/5/options/#boolean-flags) don't set `type` when creating boolean flags with secondary options (i.e., ``--something/--no-something``), so I followed that example.
> BUG: fixes broken boolean flag handler

- q2cli/commands.py
- q2cli/handlers.py
- q2cli/tests/test_cli.py
Adds a `--verbose` flag to plugin action commands (off by default) that displays any stdout/stderr generated by an action.
Also fixed two bugs in --cmd-config option:
- supplying a value in config was ignored if the option had a default value
- boolean flags in config did not work correctly; any value was evaluated as true except for the empty value, and the value (as a `str`) was forwarded to the action instead of being converted to a `bool` type.
Also improved error message for when `--output-dir` directory already exists (previously was a traceback, now is a nicely formatted Click echo).
Fixes #64.
> ENH/BUG: add --verbose flag; fix two --cmd-config bugs

- q2cli/tests/test_cli.py
Provenance added a parameter to `_from_view()`. Imported and added  required `ImportProvenanceCapture` to get tests to pass.
> TST: Fix missing provenance from test setup

- q2cli/handlers.py
Before this change, the handler would try to load the `qiime.Metadata` object passing `path=None`. 
@ebolyen, @jairideout does this fix look right to you? I'm not too familiar with this code, but it's now handled essentially the same way as in `RegularParameterHandler`, and the command below now works. 
```bash
$ qiime feature-table filter-samples --i-table table.qza --o-filtered-table junk --p-min-frequency 2000 --p-max-frequency 4000
Traceback (most recent call last):
File "/Users/caporaso/Google Drive/code/qiime2/qiime2/qiime/metadata.py", line 25, in load
df = pd.read_csv(path, sep='\t', dtype=object)
File "/Users/caporaso/miniconda3/envs/qiime2-dev/lib/python3.5/site-packages/pandas/io/parsers.py", line 562, in parser_f
return _read(filepath_or_buffer, kwds)
File …
```
> ENH: support optional metadata on command line

- q2cli/tools.py
`tools export` now matches the interface of `tools extract` since they perform similar operations. Updated, expanded, and normalized help text for `tools import`, `tools export`, and `tools extract` as they are all related operations.
> ENH: match interfaces for `tools export` and `tools extract` commands

- README.md
- bin/tab-qiime
- q2cli/__main__.py
Fixes #91 
Note: apparently `path` was overwriting the shell variable `$PATH` in ZSH, which was why this wasn't working previously.
> ENH: Add support for ZSH tab-completion

- q2cli/tools.py
Visualizations have a `format` of `None` which did not work with
`click.secho`. The "Data format:" section of the output is now omitted
for visualizations as it is not relevant.
Fixes #101
> BUG: Fix `qiime tools peek` for visualizations

- q2cli/tools.py
Previously `qiime tools view` would "work" and just not alert the user that it won't actually work in a headless environment.
Resolves #103 
*Question*
Wasn't entirely sure on how to word the message, does it sound ok, or need tweaks?
Test run
```
(qiime)jakereps@bacon:~$ qiime tools view blah.txt
Usage: qiime tools view [OPTIONS] VISUALIZATION_PATH
Error: Visualization viewing is currently not supported on headless environments. You can provide a public path to your file at https://view.qiime2.org, or move the Visualization to your local machine and view it through qiime tools view.
(qiime)jakereps@bacon:~$ 
```
> ENH: Disallow viewing on headless environments.

- q2cli/commands.py
Catches and warns of potentially invalid characters that can occur from code being placed in a text editor that tries too hard.
```bash
(qiime2) [16:42] q2cli (emdash) $ qiime —version
Error: Detected invalid character in: —version
Verify the correct quotes or dashes (ASCII) are being used.
(qiime2) [16:42] q2cli (emdash) $ qiime test-plugin blocking-test --i-table ~/Documents/qiime2-moving-pictures-tutorial/table.qza --o-rarefied-table blah —p-timeout 5
Error: Detected invalid character in: —p-timeout
Verify the correct quotes or dashes (ASCII) are being used.
```
Resolves #107
> ENH: Validate proper input characters

- q2cli/commands.py
Resolves #98 
Thoughts on verbiage? `Saved to:` `Written to:` `<filepath only>`. Extend the filepath beyond the relative path that is returned by `.save()`?
```
(qiime2) [17:09] qiime2-moving-pictures-tutorial $ qiime diversity beta-group-significance --i-distance-matrix cm1441/unweighted_unifrac_distance_matrix.qza --m-metadata-file sample-metadata.tsv --m-metadata-category BodySite --o-visualization cm1441/unweighted-unifrac-body-site-significance
Saved to: cm1441/unweighted-unifrac-body-site-significance.qzv
(qiime2) [17:09] qiime2-moving-pictures-tutorial $ 
```
> ENH: Add feedback to result saving

- .travis.yml
- LICENSE
- q2cli/__init__.py
- q2cli/__main__.py
- q2cli/cache.py
- q2cli/commands.py
- q2cli/completion.py
- q2cli/dev.py
- q2cli/handlers.py
- q2cli/info.py
- q2cli/tests/test_cli.py
- q2cli/tools.py
- q2cli/util.py
- setup.py
`qiime` package is now `qiime2`.
New date-based versioning scheme is:
- YYYY.M.patch.dev0 for development version (e.g. 2017.2.0.dev0, 2017.2.1.dev0,
2018.10.0.dev0)
- YYYY.M.patch for release version (e.g. 2017.2.0, 2017.2.1, 2018.10.0)
Plugins/interfaces are recommended to specify `qiime2 == YYYY.M.*` in
setup.py's `install_requires` to obtain patch releases for a given train
release.
The new versioning scheme is PEP 440 compliant.
> ENH: new date-based versioning; `qiime` -> `qiime2` package rename

- q2cli/dev.py
The command was only a thin wrapper around Cookiecutter, which already has a Python API and CLI. It's easier to have plugin devs use Cookiecutter directly when templating a plugin, and lets us remove Cookiecutter as a framework dependency. There are instructions on the QIIME 2 docs site for using Cookiecutter.
> ENH: remove `qiime dev plugin-init` in favor of direct Cookiecutter usage

- .travis.yml
- q2cli/cache.py
Entry point discovery code is (mostly) duplicated from the framework's code (this is intentional; the duplication can be removed when https://github.com/qiime2/qiime2/issues/151 is fixed). This commit brings the CLI code up-to-speed with changes to the framework's code in https://github.com/qiime2/qiime2/pull/216.
> MAINT: sync entry point discovery with framework

- q2cli/cache.py
- q2cli/commands.py
- q2cli/info.py
Added `short_description` of each installed plugin to print statement from `qiime info` output, and `description` from any given plugin to the output from running `qiime --help name-of-that-plugin`.
A simple test example can be seen in the output quoted [in my pull request to `q2-feature-table`](https://github.com/qiime2/q2-feature-table/pull/91).
> `short_description` and `description` in output

- q2cli/commands.py
- q2cli/handlers.py
Adds `--quiet` flag to `q2cli` that will suppress the success message once a method has been ran and the result objects saved.
Resolves #125
> ENH: Add --quiet flag to method calls

- q2cli/tests/test_cli.py
- q2cli/tools.py
I expected to get the set of importable types via `qiime2.sdk.PluginManager.importable_types`, but that just results in a property object.
```bash
(qiime2-dev) [aas229@wind ~/projects/qiime_dev/q2cli ]$ qiime tools import --show-importable-types
<property object at 0x7f1adf7b8318>
```
How can I actually access the set of importable types?
> attempt to add --show-importable-types option

- q2cli/__init__.py
- q2cli/core.py
- q2cli/handlers.py
- q2cli/info.py
- q2cli/tests/test_core.py
- q2cli/tools.py
Click allows options to be repeated on the command line and stores the value of the last specified option (this is to support overriding options set in shell aliases). While this is common behavior in CLI tools, it is prevented in q2cli to avoid confusion with options that are intended to be supplied multiple times (``multiple=True``; Click calls these "multiple options"). QIIME 2 metadata is an example of a "multiple option" in q2cli.
To support this behavior, q2cli now has ``q2cli.Option`` and ``@q2cli.option``, which are intended to be drop-in replacements for their Click counterparts.
Fixes #143.
> BUG: disallow repeated options

- q2cli/handlers.py
- q2cli/tests/test_cli.py
- q2cli/tests/test_core.py
Please "Squash and Merge" with the following content as the commit message (the PR title is fine to use as the commit message title):
Adds support for supplying multiple `--m-metadata-file` options, including usage with a metadata category. If multiple metadata files are provided they are merged.
Refactored (mostly rewrote) `MetadataHandler` and `MetadataCategoryHandler` to reduce code duplication. `MetadataCategoryHandler` now composes with `MetadataHandler`.
Added fairly comprehensive unit tests for metadata support in q2cli (there weren't really existing tests for metadata).
Fixed a bug where a metadata category's `description` wasn't displayed in help text.
Fixes #140.
> ENH: support multiple metadata options (metadata merging)

- q2cli/handlers.py
We should transition from calling these "metadata mapping files" to "metadata files", as the term "mapping" doesn't really get us much.
> MAINT: clarify help text

- q2cli/commands.py
Removed trailing period from the debug log message, making it possible to double-click on the path name (e.g. to copy and paste) in terminal emulators. Previously, double-clicking on the log path would include the trailing period, which is usually not what you want.
> ENH: debug log path is easier to select

- .travis.yml
- Makefile
Previously:
```
QIIMETEST= make test
```
Now:
```
make test
```
:tada:
Also removed the `test-cov` target because coverage isn't set up for this package (yet).
> ENH: let `make test` handle QIIMETEST env var

- q2cli/util.py
Using `textwrap.wrap` in `q2cli.util.exit_with_error` was swallowing newlines in the error messages it displays, and sometimes these newlines are important to separate sections of content within the error message (e.g. `validate` errors from the framework). By avoiding text wrapping, the original formatting of the error message is preserved.
This change is in line with the goals of #146 by avoiding explicit text wrapping within q2cli.
> BUG: remove text wrapping from error handling util

- q2cli/tests/test_cli.py
- q2cli/util.py
This branch was lost in the refactor of #166, busywork caught the issue right away.
> BUG: fix missing primitive lookup

- q2cli/handlers.py
- q2cli/tools.py
Updated `click.Path` usage throughout q2cli to use the parameters `exists`, `file_okay`, `dir_okay`, `writable`, and `readable` in the appropriate way in order to allow Click to handle path-related errors, such as file/directory not found, permissions issues, and file vs directory acceptance criteria.
Previously many of these path-related errors were being caught and handled at a lower level in the framework (e.g. Archiver), resulting in Python exceptions being displayed on the CLI, which may be hard to interpret in the context of q2cli usage.
Also, `qiime tools validate` now shows its default value for `--level` (i.e.  "max") when running in `--help` mode.
`click.Path` API reference: http://click.pocoo.org/6/api/#click.Path
> ENH: leverage click.Path for error handling

- q2cli/commands.py
- q2cli/handlers.py
- q2cli/tests/test_cli.py
- q2cli/tests/test_core.py
Detects old-style metadata category option names and suggests new names.
Describes expected metadata column type(s) in help text (metavar).
Raises informative and well-formatted error messages if a column can't be found or the column is an incorrect type.
See qiime2/qiime2#359 for details.
> MAINT: new Metadata updates

- q2cli/handlers.py
The former API no longer exists.
Depends on https://github.com/qiime2/qiime2/pull/366
> MAINT: use `Artifact.view(Metadata)` instead of `Metadata.from_artifact`

- q2cli/handlers.py
- q2cli/tests/test_cli.py
Previously, when a single Metadata was provided as input, the ID header was
normalized to 'id' instead of keeping the original value (e.g. '#SampleID').
New behavior is to retain original ID header when not merging, and normalize
the ID header to 'id' when a merge happens.
Depends on https://github.com/qiime2/qiime2/pull/367
> BUG: preserve Metadata ID header when not merging Metadata

- q2cli/tests/test_tools.py
- q2cli/tools.py
This should correct issues with cross-device links (e.g. os.rename).
I don't have an obvious way to test this, but I could try something with mocks maybe.
TODO:
> BUG: fixes export for EXDEV situations

- q2cli/builtin/tools.py
> MAINT: Updated helptext to display the correct command

- q2cli/core/completion.py
Ran into this at STAMPS. A root conda environment (like `/opt/`) will not allow users to tab-complete as they do not have the executable bit set.
Tested manually by inspection of the flags.
cc @AstrobioMike
> BUG: fix completion permissions for root installed env

- q2cli/click/command.py
- q2cli/commands.py
- q2cli/core/config.py
- q2cli/util.py
Some text was still using `click.secho` not `CONFIG.cfg_style`. I think I replaced all relevant instances of this.
> MAINT: Replace some remaining sechos with CONFIG.cfg_style

- .gitignore
- q2cli/commands.py
- q2cli/core/cache.py
This PR is meant to reduce time needed to generate action help text (Issue https://github.com/qiime2/docs/issues/429). The Deprecated API was previously using the Plugin Manager to check for a `deprecated` field in each plugin action. Use of the Plugin Manager to access the state of a plugin action makes action help text generation slow.
The state for plugins and plugin actions are initialized whenever a new conda environment is created, or when the cache is refreshed using the command `qiime dev refresh-cache`. This PR adds a deprecated field while checking the state of each plugin action. The `state.json` file is then "written to" with the updated state fields (including the deprecated field), and is used to provide quick access to plugin action state information. 
See timed results for …
> MAINT: Reduce time to generate action help text

- q2cli/commands.py
Paren was in the wrong place causing a TypeError and traceback.
> BUG: keyword error from misplaced paren

- q2cli/click/type.py
Fixes #231.
The code was close, but `is_writable_dir` only cares about permissions, we still need to make sure it exists.
> BUG: catch missing output directories first

- q2cli/click/option.py
- q2cli/click/type.py
Closes #222 by making the error message look more in line with the current error that can be thrown by `type_cast_value`. This is the error message:
> IMP: Improved error message when inappropriate primitive passed

- q2cli/core/usage.py
this work came up in a discussion with @andrewsanchez - having a `render` method on all of the usage drivers would help simplify his life when building sphinx-ext-qiime2. I plan to follow up to make that `render` method part of the base `Usage` class API.
Also, while working on this I had some ideas for refactoring the CLI-specific usage cache, more on that later.
> refactor: usage renderer logic is now fully priv

- Makefile
- q2cli/core/usage.py
When mutliple `use.view_as_metadata()` where used on the same original variable (with different names provided), a namespace collision occurs. This happened because the variable returned by super() was actually named after the metadata variable, rather than the user supplied variable.
Behavior is still the same as the interface_name is still immediately overwritten.
> BUG: fix namespace collision when names differ

- q2cli/click/option.py
Click is really ending up as a mess for us. We've already gutted a ton of the original source by this point. How much more can it take? 
https://github.com/pallets/click/pull/2293
> HACK: fix List[Bool] types (found by mystery-stew)

- q2cli/tests/test_tools.py
this PR fixes a bug in the unit tests for cache that required user permissions to be manually set for osx
> bug: adds user permissions in cache testing for osx

- q2cli/commands.py
- q2cli/tests/test_cache_cli.py
- q2cli/util.py
Raises a better error when trying to use a cache:key as an output dir
> Cache cli output dir

- q2cli/builtin/tools.py
- q2cli/util.py
Allows for a cache:key to be handed to `qiime tools view`. Also allows visualizations to be saved to cache using `qiime tools cache-save`
> View in cache

- q2cli/builtin/tools.py
- q2cli/tests/test_tools.py
Renames cache-save/load to cache-store/fetch and standardizes to --cache-path
> SQUASH: Rename tools and args

- q2cli/commands.py
Changed stdout on action completion to differentiate between artifacts added to a cache and artifacts saved to a standard file. 
See #285.
> IMP: differentiate stdout between cache entry and file output

- q2cli/builtin/tools.py
- q2cli/commands.py
- q2cli/tests/test_cli.py
- q2cli/tests/test_tools.py
Added two commands to show the available semantic types and importable and exportable formats for a qiime deployment. 
Will replace the functionality of the `qiime tools import --show-importable-types` and `qiime tools import --show-importable-formats` commands.
Additionally:
- descriptions are given of each semantic type or format when available
- semantic types or formats can be subsetted to only those of interest 
- a `--tsv` flag is available
Motivated by #289.
> FEAT: qiime tools show-types and qiime tools show-formats commands
